---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "RoleBinding"
metadata:
  annotations: {}
  name: "nginx-ingress"
  labels:
    app: "nginx-ingress"
    heritage: "Tiller"
    app.kubernetes.io/name: "nginx-ingress-1"
    chart: "nginx-ingress-1.41.3"
    release: "nginx-ingress"
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "Role"
  name: "nginx-ingress"
subjects:
- kind: "ServiceAccount"
  name: "nginx-ingress"
  namespace: "nginx-ingress"
