---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  annotations: {}
  name: "nginx-ingress"
  labels:
    app: "nginx-ingress"
    heritage: "Tiller"
    app.kubernetes.io/name: "nginx-ingress-1"
    chart: "nginx-ingress-1.41.3"
    release: "nginx-ingress"
